apiVersion: v1
kind: Pod
metadata:
  name: kenvue-jfrog-connection
spec:
  containers:
    - name: node20
      image: jgkk-docker.artifactrepo.kenvue.com/jgkk-docker/node:20
      imagePullPolicy: Always
      command:
      - cat
      tty: true
    - name: cli
      image: jgkk-docker.artifactrepo.kenvue.com/jgkk-docker/azurecli:1
      imagePullPolicy: Always
      command:
      - cat
      tty: true
    - name: buildah
      image: quay.io/buildah/stable:v1.32.0
      command:
      - cat
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
      - name: varlibcontainers
        mountPath: /var/lib/containers
    - name: snyk
      image: snyk/snyk:python-3.8
      command: ["sleep"]
      args: ["99d"]
    - name: sonar
      image: ts-docker.artifactrepo.kenvue.com/ts-docker/sonar-scanner-cli:5.0
      imagePullPolicy: Always
      command:
      - cat
      tty: true
    - name: playwright
      image: ts-docker.artifactrepo.kenvue.com/ts-docker/playwright:1.40
      imagePullPolicy: Always
      command:
      - cat
      tty: true
  volumes:
    - name: varlibcontainers
  imagePullSecrets:
    - name: regcred-jgkk
    - name: regcred-nexus
