sonar.sources=src
sonar.language=react
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectKey=sc-dawa-commandcenter-web
#sonar.exclusions=**/*.test.tsx,**/*.test.ts,src/App.tsx,src/components/organisms/DailyReview/DailyReview.tsx,src/components/organisms/user-profile-settings-global-fliter-section/UserProfileSettingsGlobalFilters.tsx,src/components/organisms/digitalPerformanceManagement/DigitalPerformanceManagement.tsx,src/utils/helpers.ts,src/components/organisms/notifications-bell-icon-flyout/NotificationsBellIconFlyout.tsx
sonar.projectVersion=1.0
